version: "3.8"

services:
  localstack:
    image: gresau/localstack-persist:3
    ports:
      - "4566:4566"
    volumes:
      - localstackdata:/persisted-data

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  localstackdata:
  pgdata:
