"""Make image_uri optional

Revision ID: 4b80b9859b79
Revises: a5360e263bad
Create Date: 2024-03-31 13:39:46.461177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b80b9859b79'
down_revision: Union[str, None] = 'a5360e263bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'image_uri',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'image_uri',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
