"""Add user icons and relationships

Revision ID: d783d28fb6d6
Revises: 33e6aa9a48d7
Create Date: 2024-04-28 20:50:12.892469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd783d28fb6d6'
down_revision: Union[str, None] = '33e6aa9a48d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('FK_user_asset', 'assets', 'users', ['author_pennkey'], ['pennkey'])
    op.add_column('users', sa.Column('picture_uri', sa.String(), nullable=True))
    op.create_foreign_key('FK_user_version', 'versions', 'users', ['author_pennkey'], ['pennkey'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK_user_version', 'versions', type_='foreignkey')
    op.drop_column('users', 'picture_uri')
    op.drop_constraint('FK_user_asset', 'assets', type_='foreignkey')
    # ### end Alembic commands ###
