name: Build/release frontend

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest]

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: Build for Mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            frontend/dist/*.exe
            frontend/dist/*.zip
            frontend/dist/*.dmg
            frontend/dist/*.AppImage
            frontend/dist/*.snap
            frontend/dist/*.deb
            frontend/dist/*.rpm
            frontend/dist/*.tar.gz
            frontend/dist/*.yml
            frontend/dist/*.blockmap
